# Generated by Django 4.1.3 on 2025-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comments',
            field=models.CharField(default='No Comments', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='Null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.DateField(auto_now=True),
        ),
    ]
